### ISSUE TITLE
The dehumidifier entity is missing after 0.7.0 upgrade

### ISSUE THREAD

**Issue by trajano** [oyvindwe/connectlife-ha#36] opened 2024-07-09 22:23 UTC
Deleted and re-added all I see is the fan speed selector

![image](https://github.com/oyvindwe/connectlife-ha/assets/110627/23415e0d-9693-47bf-b110-73b0f612d243)

So likely there are changes on `humidifier` that broke this.

_Originally posted by @trajano in https://github.com/oyvindwe/connectlife-ha/issues/22#issuecomment-2218791226_

**Comment by oyvindwe** [comment] 2024-07-09 23:29
I got the error in my log:
```
2024-07-10 01:18:31.183 ERROR (MainThread) [homeassistant.components.humidifier] Error while setting up connectlife platform for humidifier
Traceback (most recent call last):
  File "/Users/omw/proj/home-assistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/Users/omw/proj/home-assistant/config/custom_components/connectlife/humidifier.py", line 41, in async_setup_entry
    entities.append(ConnectLifeHumidifier(coordinator, appliance, dictionary))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omw/proj/home-assistant/config/custom_components/connectlife/humidifier.py", line 109, in __init__
    self._attr_min_humidity = data_dictionary[status].climate.min_value
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Property' object has no attribute 'climate'
```

Regression error due to poor testing of humidifier - apologies for that. Fixed in version 0.7.1

**Closed by oyvindwe** 2024-07-09 23:29 UTC
